# ============================================================
# IOE-DREAM Gateway 临时修复配置
# 将所有 lb:// 服务发现路由改为直接地址路由
# ============================================================

# 临时解决方案：重启gateway服务
# 1. 停止当前gateway服务
# 2. 使用此配置替换 application.yml
# 3. 重启gateway服务

spring:
  cloud:
    gateway:
      routes:
        # 登录认证路由（直接指向common-service）
        - id: ioedream-login-service
          uri: http://localhost:8088
          predicates:
            - Path=/login/**,/logout/**,/captcha/**
          filters:
            - StripPrefix=0

        # 公共业务服务路由（直接指向common-service）
        - id: ioedream-common-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/system/**,/api/v1/notification/**,/api/v1/area-device/**,/api/v1/area-permission/**,/api/v1/auth/**,/api/v1/menu/**,/admin/**,/oa/**,/support/**,/home/**,/file/**,/goods/**,/category/**,/employee/**,/department/**,/role/**,/menu/**,/helpdoc/**,/changeLog/**,/feedback/**,/config/**,/datascope/**,/dict/**,/serial-number/**,/reload/**,/heart-beat/**,/system/**
          filters:
            - StripPrefix=0

        # 设备通讯服务路由（暂时注释，服务未启动）
        # - id: ioedream-device-comm-service
        #   uri: http://localhost:8087
        #   predicates:
        #     - Path=/api/v1/device/**,/api/v1/biometric/**
        #   filters:
        #     - StripPrefix=0

        # 门禁管理服务路由（暂时注释，服务未启动）
        # - id: ioedream-access-service
        #   uri: http://localhost:8090
        #   predicates:
        #     - Path=/api/v1/access/**,/api/v1/mobile/access/**
        #   filters:
        #     - StripPrefix=0

        # 其他服务路由（暂时注释）
        # ... 其他路由类似处理

# ==================== 使用说明 ====================
# 1. 将此配置内容复制到 application.yml 中的 gateway.routes 部分
# 2. 重启 gateway 服务
# 3. 测试登录接口：curl -X GET http://localhost:8080/login/getTwoFactorLoginFlag
# 4. 如果成功，说明问题已解决
# 5. 后续可以逐步恢复服务发现功能