-- 消费账户表
CREATE TABLE IF NOT EXISTS `t_consume_account` (
  `account_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '账户ID',
  `person_id` BIGINT NOT NULL COMMENT '人员ID（主键关联）',
  `person_name` VARCHAR(64) NOT NULL COMMENT '人员姓名',
  `employee_no` VARCHAR(32) NULL COMMENT '员工编号',
  `account_no` VARCHAR(64) NOT NULL COMMENT '账户编号（系统生成的唯一标识）',
  `balance` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '可用余额',
  `frozen_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '冻结金额',
  `credit_limit` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '信用额度',
  `available_limit` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '可用额度（余额 + 信用额度 - 冻结金额）',
  `account_type` VARCHAR(32) NOT NULL DEFAULT 'STAFF' COMMENT '账户类型 STAFF/STUDENT/VISITOR/TEMP',
  `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '账户状态 ACTIVE/FROZEN/CLOSED/SUSPENDED',
  `region_id` VARCHAR(64) NULL COMMENT '所属区域ID',
  `region_name` VARCHAR(128) NULL COMMENT '所属区域名称',
  `department_id` BIGINT NULL COMMENT '部门ID',
  `department_name` VARCHAR(128) NULL COMMENT '部门名称',
  `account_level` VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '账户等级 NORMAL/VIP/PLATINUM',
  `points` INT NOT NULL DEFAULT 0 COMMENT '积分余额',
  `total_consume_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计消费金额',
  `total_recharge_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计充值金额',
  `last_consume_time` DATETIME NULL COMMENT '最后消费时间',
  `last_recharge_time` DATETIME NULL COMMENT '最后充值时间',
  `account_create_time` DATETIME NOT NULL COMMENT '账户创建时间',
  `active_time` DATETIME NULL COMMENT '账户激活时间',
  `freeze_time` DATETIME NULL COMMENT '账户冻结时间',
  `close_time` DATETIME NULL COMMENT '账户关闭时间',
  `freeze_reason` VARCHAR(512) NULL COMMENT '冻结原因',
  `close_reason` VARCHAR(512) NULL COMMENT '关闭原因',
  `monthly_limit` DECIMAL(12,2) NULL COMMENT '月度消费限额',
  `daily_limit` DECIMAL(12,2) NULL COMMENT '日度消费限额',
  `single_limit` DECIMAL(12,2) NULL COMMENT '单次消费限额',
  `current_monthly_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '当前月度已消费金额',
  `current_daily_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '当前日度已消费金额',
  `password` VARCHAR(255) NULL COMMENT '密码（用于消费验证）',
  `pay_password` VARCHAR(255) NULL COMMENT '支付密码',
  `card_id` VARCHAR(64) NULL COMMENT '卡片ID（物理卡）',
  `card_status` VARCHAR(16) NULL DEFAULT 'NORMAL' COMMENT '卡片状态 NORMAL/LOST/DAMAGE/EXPIRED',
  `face_feature_id` VARCHAR(128) NULL COMMENT '人脸特征标识',
  `fingerprint_id` VARCHAR(128) NULL COMMENT '指纹特征标识',
  `phone_number` VARCHAR(20) NULL COMMENT '手机号码（用于通知和验证）',
  `email` VARCHAR(128) NULL COMMENT '邮箱地址（用于通知）',
  `account_config` JSON NULL COMMENT '账户配置JSON（存储个性化配置）',
  `extend_data` JSON NULL COMMENT '扩展数据JSON（存储扩展字段）',
  `sms_notification` TINYINT NOT NULL DEFAULT 0 COMMENT '是否开启短信通知',
  `email_notification` TINYINT NOT NULL DEFAULT 0 COMMENT '是否开启邮件通知',
  `consume_reminder` TINYINT NOT NULL DEFAULT 1 COMMENT '是否开启消费提醒',
  `reminder_threshold` DECIMAL(12,2) NOT NULL DEFAULT 50.00 COMMENT '消费提醒阈值（低于此金额时提醒）',
  `auto_recharge` TINYINT NOT NULL DEFAULT 0 COMMENT '自动充值开关',
  `auto_recharge_threshold` DECIMAL(12,2) NULL COMMENT '自动充值阈值',
  `auto_recharge_amount` DECIMAL(12,2) NULL COMMENT '自动充值金额',
  `payment_methods` JSON NULL COMMENT '绑定支付方式（JSON格式：微信、支付宝、银行卡等）',
  `remark` VARCHAR(512) NULL COMMENT '备注信息',
  -- 审计字段
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `create_user_id` BIGINT NULL,
  `update_user_id` BIGINT NULL,
  `deleted_flag` TINYINT NOT NULL DEFAULT 0,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`account_id`),
  UNIQUE KEY `uk_account_no` (`account_no`),
  UNIQUE KEY `uk_person_id` (`person_id`),
  UNIQUE KEY `uk_employee_no` (`employee_no`),
  UNIQUE KEY `uk_card_id` (`card_id`),
  KEY `idx_person_id` (`person_id`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_account_type` (`account_type`),
  KEY `idx_status` (`status`),
  KEY `idx_account_level` (`account_level`),
  KEY `idx_last_consume_time` (`last_consume_time`),
  KEY `idx_last_recharge_time` (`last_recharge_time`),
  KEY `idx_balance` (`balance`),
  KEY `idx_credit_limit` (`credit_limit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='消费账户表';

-- 消费设备配置表
CREATE TABLE IF NOT EXISTS `t_consume_device_config` (
  `config_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '配置ID',
  `device_id` BIGINT NOT NULL COMMENT '设备ID（关联设备管理表）',
  `device_name` VARCHAR(128) NOT NULL COMMENT '设备名称',
  `device_no` VARCHAR(64) NOT NULL COMMENT '设备编号（唯一标识）',
  `device_type` VARCHAR(32) NOT NULL COMMENT '设备类型 POS/DOOR/TURNTABLE/KIOSK/VENDING等',
  `region_id` VARCHAR(64) NULL COMMENT '所属区域ID',
  `region_name` VARCHAR(128) NULL COMMENT '所属区域名称',
  `location` VARCHAR(256) NULL COMMENT '设备位置描述',
  `coordinates` VARCHAR(64) NULL COMMENT '设备安装位置（经纬度）',
  `supported_modes` VARCHAR(255) NOT NULL COMMENT '支持的消费模式（逗号分隔：FIXED_AMOUNT,FREE_AMOUNT,METERING等）',
  `default_mode` VARCHAR(32) NOT NULL COMMENT '默认消费模式',
  `status` VARCHAR(16) NOT NULL DEFAULT 'OFFLINE' COMMENT '设备状态 ONLINE/OFFLINE/MAINTENANCE/ERROR/DISABLED',
  `priority` INT NOT NULL DEFAULT 0 COMMENT '设备配置优先级（数值越大优先级越高）',
  `ip_address` VARCHAR(45) NULL COMMENT '设备IP地址',
  `mac_address` VARCHAR(17) NULL COMMENT '设备MAC地址',
  `serial_number` VARCHAR(128) NULL COMMENT '设备序列号',
  `firmware_version` VARCHAR(32) NULL COMMENT '设备固件版本',
  `software_version` VARCHAR(32) NULL COMMENT '设备软件版本',
  `manufacturer` VARCHAR(128) NULL COMMENT '设备制造商',
  `model` VARCHAR(128) NULL COMMENT '设备型号',
  `install_time` DATETIME NULL COMMENT '设备安装时间',
  `online_time` DATETIME NULL COMMENT '设备上线时间',
  `last_heartbeat_time` DATETIME NULL COMMENT '最后心跳时间',
  `offline_time` DATETIME NULL COMMENT '设备离线时间',
  `enable_time` DATETIME NULL COMMENT '设备启用时间',
  `disable_time` DATETIME NULL COMMENT '设备禁用时间',
  `mode_config` JSON NULL COMMENT '消费模式配置JSON（存储模式特定的配置参数）',
  `hardware_config` JSON NULL COMMENT '设备硬件配置JSON',
  `network_config` JSON NULL COMMENT '设备网络配置JSON',
  `security_config` JSON NULL COMMENT '设备安全配置JSON',
  `extend_data` JSON NULL COMMENT '扩展数据JSON（存储扩展字段）',
  `offline_mode` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用离线模式',
  `offline_sync_mode` VARCHAR(16) NULL DEFAULT 'AUTO' COMMENT '离线数据同步方式 AUTO/MANUAL',
  `offline_storage_capacity` INT NULL DEFAULT 1024 COMMENT '离线数据存储容量（MB）',
  `offline_sync_interval` INT NULL DEFAULT 300 COMMENT '离线数据同步间隔（秒）',
  `auto_restart` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用自动重启',
  `restart_interval` INT NULL DEFAULT 24 COMMENT '自动重启时间间隔（小时）',
  `remote_control` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用远程控制',
  `remote_control_permissions` JSON NULL COMMENT '远程控制权限（JSON格式）',
  `real_time_monitoring` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用实时监控',
  `monitoring_interval` INT NULL DEFAULT 60 COMMENT '监控数据上报间隔（秒）',
  `admin_user_id` BIGINT NULL COMMENT '设备管理员ID',
  `admin_user_name` VARCHAR(64) NULL COMMENT '设备管理员姓名',
  `support_phone` VARCHAR(20) NULL COMMENT '技术支持联系电话',
  `support_email` VARCHAR(128) NULL COMMENT '技术支持邮箱',
  `maintenance_cycle` INT NULL DEFAULT 30 COMMENT '设备维护周期（天）',
  `last_maintenance_time` DATETIME NULL COMMENT '最后维护时间',
  `next_maintenance_time` DATETIME NULL COMMENT '下次维护时间',
  `usage_count` BIGINT NOT NULL DEFAULT 0 COMMENT '设备使用次数统计',
  `usage_hours` BIGINT NOT NULL DEFAULT 0 COMMENT '设备使用时长统计（小时）',
  `failure_count` INT NOT NULL DEFAULT 0 COMMENT '设备故障次数',
  `status_code` VARCHAR(32) NULL COMMENT '设备运行状态码',
  `status_description` VARCHAR(512) NULL COMMENT '设备运行状态描述',
  `performance_metrics` JSON NULL COMMENT '设备性能指标JSON（CPU、内存、磁盘等）',
  `enable_logging` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用设备日志',
  `log_retention_days` INT NULL DEFAULT 30 COMMENT '日志保留天数',
  `enable_encryption` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用数据加密',
  `encryption_key_version` VARCHAR(16) NULL COMMENT '加密密钥版本',
  `device_tags` JSON NULL COMMENT '设备标签（JSON格式，用于分组管理）',
  `device_group` VARCHAR(64) NULL COMMENT '设备分组',
  `remark` VARCHAR(512) NULL COMMENT '备注',
  -- 审计字段
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `create_user_id` BIGINT NULL,
  `update_user_id` BIGINT NULL,
  `deleted_flag` TINYINT NOT NULL DEFAULT 0,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`config_id`),
  UNIQUE KEY `uk_device_id` (`device_id`),
  UNIQUE KEY `uk_device_no` (`device_no`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_device_type` (`device_type`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`),
  KEY `idx_last_heartbeat_time` (`last_heartbeat_time`),
  KEY `idx_device_group` (`device_group`),
  KEY `idx_composite_region_type` (`region_id`, `device_type`),
  KEY `idx_composite_status_priority` (`status`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='消费设备配置表';

-- 消费记录表
CREATE TABLE IF NOT EXISTS `t_consume_record` (
  `record_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `employee_id` BIGINT NULL COMMENT '员工ID（兼容旧系统）',
  `person_id` BIGINT NOT NULL COMMENT '人员ID（主键关联）',
  `person_name` VARCHAR(64) NOT NULL COMMENT '人员姓名',
  `consume_date` DATE NULL COMMENT '消费日期',
  `amount` DECIMAL(12,2) NOT NULL COMMENT '消费金额',
  `consume_amount` DECIMAL(12,2) NULL COMMENT '消费金额别名（与amount相同，兼容旧系统）',
  `balance_before` DECIMAL(12,2) NULL COMMENT '消费前余额',
  `balance_after` DECIMAL(12,2) NULL COMMENT '消费后余额',
  `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种（默认CNY）',
  `consume_type` VARCHAR(32) NULL COMMENT '消费类型（兼容旧系统：MEAL/SNACK/DRINK/OTHER）',
  `pay_method` VARCHAR(16) NOT NULL COMMENT '支付方式 CARD/WALLET/CASH',
  `order_no` VARCHAR(64) NOT NULL COMMENT '订单号（唯一标识）',
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '交易状态 SUCCESS/FAILED/REFUND/PENDING',
  `pay_time` DATETIME NULL COMMENT '支付时间',
  `device_id` BIGINT NULL COMMENT '设备ID',
  `device_name` VARCHAR(128) NULL COMMENT '设备名称',
  `consumption_mode` VARCHAR(32) NULL COMMENT '消费模式 FIXED_AMOUNT/FREE_AMOUNT/METERING/PRODUCT/ORDERING/SMART',
  `region_id` VARCHAR(64) NULL COMMENT '区域ID',
  `region_name` VARCHAR(128) NULL COMMENT '区域名称',
  `account_type` VARCHAR(32) NULL COMMENT '账户类型 STAFF/STUDENT/VISITOR/TEMP',
  `remark` VARCHAR(512) NULL COMMENT '备注',
  `mode_config` JSON NULL COMMENT '消费模式配置JSON（存储使用的配置参数）',
  `extend_data` JSON NULL COMMENT '扩展数据JSON（存储扩展字段）',
  `client_ip` VARCHAR(45) NULL COMMENT '终端IP地址',
  `transaction_id` VARCHAR(128) NULL COMMENT '交易流水号（银行或第三方支付返回）',
  `third_party_order_no` VARCHAR(128) NULL COMMENT '第三方支付订单号',
  `fee_amount` DECIMAL(12,2) NULL COMMENT '手续费',
  `refund_amount` DECIMAL(12,2) NULL COMMENT '退款金额',
  `refund_time` DATETIME NULL COMMENT '退款时间',
  `refund_reason` VARCHAR(512) NULL COMMENT '退款原因',
  `original_record_id` BIGINT NULL COMMENT '关联的原始交易记录ID（用于退款）',
  -- 审计字段
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `create_user_id` BIGINT NULL,
  `update_user_id` BIGINT NULL,
  `deleted_flag` TINYINT NOT NULL DEFAULT 0,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`record_id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_person_id` (`person_id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_pay_time` (`pay_time`),
  KEY `idx_consume_date` (`consume_date`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_consumption_mode` (`consumption_mode`),
  KEY `idx_status` (`status`),
  KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_original_record_id` (`original_record_id`),
  KEY `idx_composite_person_time` (`person_id`, `pay_time`),
  KEY `idx_composite_region_time` (`region_id`, `pay_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='消费记录表';


