-- 企业OA系统数据库表
-- 创建时间: 2025-11-16
-- 说明: 企业办公自动化相关数据表

-- 1. 工作流定义表
DROP TABLE IF EXISTS t_workflow_definition;
CREATE TABLE t_workflow_definition (
    workflow_def_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '工作流定义ID',
    workflow_code VARCHAR(50) NOT NULL UNIQUE COMMENT '工作流编码',
    workflow_name VARCHAR(100) NOT NULL COMMENT '工作流名称',
    workflow_type VARCHAR(30) NOT NULL COMMENT '工作流类型(LEAVE-请假,EXPENSE-报销,PURCHASE-采购,APPROVAL-审批)',
    workflow_category VARCHAR(30) COMMENT '工作流分类',
    workflow_version VARCHAR(20) NOT NULL DEFAULT '1.0' COMMENT '工作流版本',
    workflow_description TEXT COMMENT '工作流描述',
    workflow_config JSON NOT NULL COMMENT '工作流配置(JSON格式)',
    start_node_id VARCHAR(50) NOT NULL COMMENT '开始节点ID',
    end_node_id VARCHAR(50) NOT NULL COMMENT '结束节点ID',
    is_enabled TINYINT DEFAULT 1 COMMENT '是否启用(0-禁用,1-启用)',
    is_published TINYINT DEFAULT 0 COMMENT '是否已发布(0-草稿,1-已发布)',
    publish_time DATETIME COMMENT '发布时间',
    effective_date DATETIME COMMENT '生效日期',
    expire_date DATETIME COMMENT '失效日期',
    usage_count INT DEFAULT 0 COMMENT '使用次数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_workflow_code (workflow_code),
    INDEX idx_workflow_type (workflow_type),
    INDEX idx_is_enabled (is_enabled),
    INDEX idx_is_published (is_published),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流定义表';

-- 2. 工作流实例表
DROP TABLE IF EXISTS t_workflow_instance;
CREATE TABLE t_workflow_instance (
    workflow_instance_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '工作流实例ID',
    workflow_def_id BIGINT NOT NULL COMMENT '工作流定义ID',
    instance_code VARCHAR(50) NOT NULL UNIQUE COMMENT '实例编码',
    instance_title VARCHAR(200) NOT NULL COMMENT '实例标题',
    instance_data JSON COMMENT '实例数据(JSON格式)',
    business_data JSON COMMENT '业务数据(JSON格式)',
    current_node_id VARCHAR(50) COMMENT '当前节点ID',
    current_node_name VARCHAR(100) COMMENT '当前节点名称',
    instance_status VARCHAR(20) NOT NULL DEFAULT 'RUNNING' COMMENT '实例状态(RUNNING-运行中,COMPLETED-已完成,TERMINATED-已终止,SUSPENDED-已挂起)',
    initiator_id BIGINT NOT NULL COMMENT '发起人ID',
    initiator_name VARCHAR(50) NOT NULL COMMENT '发起人姓名',
    initiator_dept_id BIGINT COMMENT '发起部门ID',
    initiator_dept_name VARCHAR(100) COMMENT '发起部门名称',
    start_time DATETIME NOT NULL COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    duration_minutes INT COMMENT '持续时长(分钟)',
    priority_level VARCHAR(20) DEFAULT 'NORMAL' COMMENT '优先级(LOW-低,NORMAL-正常,HIGH-高,URGENT-紧急)',
    deadline_time DATETIME COMMENT '截止时间',
    overdue_reason TEXT COMMENT '超时原因',
    terminate_reason TEXT COMMENT '终止原因',
    attachment_count INT DEFAULT 0 COMMENT '附件数量',
    comment_count INT DEFAULT 0 COMMENT '评论数量',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_workflow_def_id (workflow_def_id),
    INDEX idx_instance_code (instance_code),
    INDEX idx_instance_status (instance_status),
    INDEX idx_initiator_id (initiator_id),
    INDEX idx_current_node_id (current_node_id),
    INDEX idx_priority_level (priority_level),
    INDEX idx_start_time (start_time),
    INDEX idx_deadline_time (deadline_time),
    FOREIGN KEY (workflow_def_id) REFERENCES t_workflow_definition(workflow_def_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流实例表';

-- 3. 工作流任务节点表
DROP TABLE IF EXISTS t_workflow_task;
CREATE TABLE t_workflow_task (
    task_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '任务ID',
    task_code VARCHAR(50) NOT NULL UNIQUE COMMENT '任务编码',
    workflow_instance_id BIGINT NOT NULL COMMENT '工作流实例ID',
    node_id VARCHAR(50) NOT NULL COMMENT '节点ID',
    node_name VARCHAR(100) NOT NULL COMMENT '节点名称',
    node_type VARCHAR(30) NOT NULL COMMENT '节点类型(START-开始,APPROVAL-审批,NOTIFY-通知,END-结束)',
    task_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态(PENDING-待处理,PROCESSING-处理中,COMPLETED-已完成,SKIPPED-已跳过)',
    task_type VARCHAR(30) NOT NULL COMMENT '任务类型(APPROVE-审批,REVIEW-审核,NOTIFY-通知,SIGN-会签)',
    assignee_id BIGINT COMMENT '处理人ID',
    assignee_name VARCHAR(50) COMMENT '处理人姓名',
    assignee_dept_id BIGINT COMMENT '处理部门ID',
    assignee_dept_name VARCHAR(100) COMMENT '处理部门名称',
    previous_task_id BIGINT COMMENT '上一任务ID',
    next_task_id BIGINT COMMENT '下一任务ID',
    task_data JSON COMMENT '任务数据(JSON格式)',
    approval_action VARCHAR(20) COMMENT '审批动作(APPROVE-同意,REJECT-拒绝,RETURN-退回,TRANSFER-转交)',
    approval_comment TEXT COMMENT '审批意见',
    approval_attachments JSON COMMENT '审批附件(JSON格式)',
    receive_time DATETIME COMMENT '接收时间',
    start_time DATETIME COMMENT '开始处理时间',
    complete_time DATETIME COMMENT '完成时间',
    duration_minutes INT COMMENT '处理时长(分钟)',
    is_parallel TINYINT DEFAULT 0 COMMENT '是否并行节点(0-否,1-是)',
    is_required TINYINT DEFAULT 1 COMMENT '是否必须处理(0-否,1-是)',
    deadline_time DATETIME COMMENT '截止时间',
    overdue_minutes INT COMMENT '超时分钟数',
    overdue_reason TEXT COMMENT '超时原因',
    delegation_user_id BIGINT COMMENT '委托处理人ID',
    delegation_user_name VARCHAR(50) COMMENT '委托处理人姓名',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_task_code (task_code),
    INDEX idx_workflow_instance_id (workflow_instance_id),
    INDEX idx_node_id (node_id),
    INDEX idx_task_status (task_status),
    INDEX idx_assignee_id (assignee_id),
    INDEX idx_task_type (task_type),
    INDEX idx_receive_time (receive_time),
    INDEX idx_deadline_time (deadline_time),
    INDEX idx_create_time (create_time),
    FOREIGN KEY (workflow_instance_id) REFERENCES t_workflow_instance(workflow_instance_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流任务节点表';

-- 4. 文档信息表
DROP TABLE IF EXISTS t_document;
CREATE TABLE t_document (
    document_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '文档ID',
    document_code VARCHAR(50) NOT NULL UNIQUE COMMENT '文档编码',
    document_name VARCHAR(200) NOT NULL COMMENT '文档名称',
    document_title VARCHAR(300) NOT NULL COMMENT '文档标题',
    document_type VARCHAR(30) NOT NULL COMMENT '文档类型(CONTRACT-合同,REPORT-报告,MANUAL-手册,FORM-表单,OTHER-其他)',
    document_category VARCHAR(50) COMMENT '文档分类',
    document_format VARCHAR(20) NOT NULL COMMENT '文档格式(PDF,WORD,EXCEL,PPT,IMAGE等)',
    file_path VARCHAR(500) NOT NULL COMMENT '文件路径',
    file_name VARCHAR(200) NOT NULL COMMENT '文件名',
    file_size BIGINT NOT NULL COMMENT '文件大小(字节)',
    file_hash VARCHAR(64) COMMENT '文件hash值',
    mime_type VARCHAR(100) COMMENT 'MIME类型',
    thumbnail_path VARCHAR(500) COMMENT '缩略图路径',
    preview_url VARCHAR(500) COMMENT '预览URL',
    download_url VARCHAR(500) COMMENT '下载URL',
    document_status VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '文档状态(DRAFT-草稿,ACTIVE-有效,EXPIRED-过期,ARCHIVED-已归档)',
    security_level VARCHAR(20) DEFAULT 'INTERNAL' COMMENT '安全级别(PUBLIC-公开,INTERNAL-内部,CONFIDENTIAL-机密,SECRET-秘密)',
    version_number VARCHAR(20) NOT NULL DEFAULT '1.0' COMMENT '版本号',
    parent_document_id BIGINT COMMENT '父文档ID',
    is_template TINYINT DEFAULT 0 COMMENT '是否模板(0-否,1-是)',
    is_encrypted TINYINT DEFAULT 0 COMMENT '是否加密(0-否,1-是)',
    is_signed TINYINT DEFAULT 0 COMMENT '是否电子签名(0-否,1-是)',
    keywords VARCHAR(500) COMMENT '关键词',
    abstract TEXT COMMENT '摘要',
    content_text LONGTEXT COMMENT '正文内容(OCR或全文提取)',
    author_id BIGINT COMMENT '作者ID',
    author_name VARCHAR(50) COMMENT '作者姓名',
    owner_id BIGINT NOT NULL COMMENT '所有者ID',
    owner_name VARCHAR(50) NOT NULL COMMENT '所有者姓名',
    dept_id BIGINT COMMENT '所属部门ID',
    dept_name VARCHAR(100) COMMENT '所属部门名称',
    effective_date DATETIME COMMENT '生效日期',
    expire_date DATETIME COMMENT '失效日期',
    retention_period INT COMMENT '保留期限(天)',
    archive_date DATETIME COMMENT '归档日期',
    access_count INT DEFAULT 0 COMMENT '访问次数',
    download_count INT DEFAULT 0 COMMENT '下载次数',
    last_access_time DATETIME COMMENT '最后访问时间',
    tag_list VARCHAR(500) COMMENT '标签列表(逗号分隔)',
    remark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_document_code (document_code),
    INDEX idx_document_type (document_type),
    INDEX idx_document_status (document_status),
    INDEX idx_security_level (security_level),
    INDEX idx_owner_id (owner_id),
    INDEX idx_dept_id (dept_id),
    INDEX idx_parent_document_id (parent_document_id),
    INDEX idx_create_time (create_time),
    INDEX idx_effective_date (effective_date),
    INDEX idx_expire_date (expire_date),
    FULLTEXT idx_document_search (document_name, document_title, keywords, abstract)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档信息表';

-- 5. 文档版本表
DROP TABLE IF EXISTS t_document_version;
CREATE TABLE t_document_version (
    version_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '版本ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    version_number VARCHAR(20) NOT NULL COMMENT '版本号',
    version_title VARCHAR(300) COMMENT '版本标题',
    version_description TEXT COMMENT '版本说明',
    file_path VARCHAR(500) NOT NULL COMMENT '文件路径',
    file_name VARCHAR(200) NOT NULL COMMENT '文件名',
    file_size BIGINT NOT NULL COMMENT '文件大小(字节)',
    file_hash VARCHAR(64) COMMENT '文件hash值',
    change_summary TEXT COMMENT '变更摘要',
    change_details JSON COMMENT '变更详情(JSON格式)',
    version_status VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '版本状态(DRAFT-草稿,ACTIVE-有效,SUPERSEDED-已替代)',
    author_id BIGINT NOT NULL COMMENT '版本作者ID',
    author_name VARCHAR(50) NOT NULL COMMENT '版本作者姓名',
    reviewer_id BIGINT COMMENT '审核人ID',
    reviewer_name VARCHAR(50) COMMENT '审核人姓名',
    review_time DATETIME COMMENT '审核时间',
    review_comment TEXT COMMENT '审核意见',
    approval_status VARCHAR(20) COMMENT '审批状态(PENDING-待审批,APPROVED-已批准,REJECTED-已拒绝)',
    approver_id BIGINT COMMENT '审批人ID',
    approver_name VARCHAR(50) COMMENT '审批人姓名',
    approval_time DATETIME COMMENT '审批时间',
    approval_comment TEXT COMMENT '审批意见',
    is_major_version TINYINT DEFAULT 0 COMMENT '是否主版本(0-否,1-是)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_document_id (document_id),
    INDEX idx_version_number (document_id, version_number),
    INDEX idx_version_status (version_status),
    INDEX idx_author_id (author_id),
    INDEX idx_create_time (create_time),
    UNIQUE KEY uk_document_version (document_id, version_number),
    FOREIGN KEY (document_id) REFERENCES t_document(document_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档版本表';

-- 6. 文档权限表
DROP TABLE IF EXISTS t_document_permission;
CREATE TABLE t_document_permission (
    permission_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '权限ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    permission_type VARCHAR(20) NOT NULL COMMENT '权限类型(USER-用户,DEPT-部门,ROLE-角色,PUBLIC-公开)',
    permission_target_id BIGINT COMMENT '权限目标ID(用户ID/部门ID/角色ID)',
    permission_target_name VARCHAR(100) COMMENT '权限目标名称',
    permission_level VARCHAR(20) NOT NULL COMMENT '权限级别(READ-只读,WRITE-可写,DELETE-删除,ADMIN-管理)',
    permission_scope VARCHAR(50) COMMENT '权限范围',
    is_granted TINYINT DEFAULT 1 COMMENT '是否授权(0-拒绝,1-授权)',
    grant_reason TEXT COMMENT '授权原因',
    effective_date DATETIME COMMENT '生效日期',
    expire_date DATETIME COMMENT '失效日期',
    grant_user_id BIGINT COMMENT '授权人ID',
    grant_user_name VARCHAR(50) COMMENT '授权人姓名',
    last_access_time DATETIME COMMENT '最后访问时间',
    access_count INT DEFAULT 0 COMMENT '访问次数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_document_id (document_id),
    INDEX idx_permission_type (permission_type),
    INDEX idx_permission_target_id (permission_target_id),
    INDEX idx_permission_level (permission_level),
    INDEX idx_is_granted (is_granted),
    INDEX idx_effective_date (effective_date),
    INDEX idx_expire_date (expire_date),
    UNIQUE KEY uk_document_permission (document_id, permission_type, permission_target_id, permission_level),
    FOREIGN KEY (document_id) REFERENCES t_document(document_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档权限表';

-- 7. 审批记录表
DROP TABLE IF EXISTS t_approval_record;
CREATE TABLE t_approval_record (
    approval_record_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '审批记录ID',
    workflow_instance_id BIGINT COMMENT '工作流实例ID',
    task_id BIGINT COMMENT '任务ID',
    document_id BIGINT COMMENT '文档ID',
    business_type VARCHAR(30) NOT NULL COMMENT '业务类型(LEAVE-请假,EXPENSE-报销,PURCHASE-采购,DOCUMENT-文档)',
    business_id BIGINT NOT NULL COMMENT '业务ID',
    business_code VARCHAR(50) NOT NULL COMMENT '业务编码',
    business_title VARCHAR(200) NOT NULL COMMENT '业务标题',
    approval_step VARCHAR(50) NOT NULL COMMENT '审批步骤',
    step_name VARCHAR(100) NOT NULL COMMENT '步骤名称',
    step_order INT NOT NULL COMMENT '步骤顺序',
    approver_id BIGINT NOT NULL COMMENT '审批人ID',
    approver_name VARCHAR(50) NOT NULL COMMENT '审批人姓名',
    approver_dept_id BIGINT COMMENT '审批部门ID',
    approver_dept_name VARCHAR(100) COMMENT '审批部门名称',
    approval_action VARCHAR(20) NOT NULL COMMENT '审批动作(APPROVE-同意,REJECT-拒绝,RETURN-退回,TRANSFER-转交,DELEGATE-委托)',
    approval_result VARCHAR(20) NOT NULL COMMENT '审批结果(PENDING-待审批,APPROVED-已同意,REJECTED-已拒绝,RETURNED-已退回)',
    approval_comment TEXT COMMENT '审批意见',
    approval_attachments JSON COMMENT '审批附件(JSON格式)',
    receive_time DATETIME COMMENT '接收时间',
    process_time DATETIME COMMENT '处理时间',
    process_duration_minutes INT COMMENT '处理时长(分钟)',
    is_required TINYINT DEFAULT 1 COMMENT '是否必须审批(0-否,1-是)',
    is_parallel TINYINT DEFAULT 0 COMMENT '是否并行审批(0-否,1-是)',
    delegation_user_id BIGINT COMMENT '委托人ID',
    delegation_user_name VARCHAR(50) COMMENT '委托人姓名',
    delegation_reason TEXT COMMENT '委托原因',
    next_step_id BIGINT COMMENT '下一步骤ID',
    next_step_name VARCHAR(100) COMMENT '下一步骤名称',
    next_approver_id BIGINT COMMENT '下一步审批人ID',
    next_approver_name VARCHAR(50) COMMENT '下一步审批人姓名',
    condition_expression VARCHAR(500) COMMENT '条件表达式',
    condition_result VARCHAR(20) COMMENT '条件结果',
    remark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_workflow_instance_id (workflow_instance_id),
    INDEX idx_task_id (task_id),
    INDEX idx_document_id (document_id),
    INDEX idx_business_type (business_type),
    INDEX idx_business_id (business_id),
    INDEX idx_approver_id (approver_id),
    INDEX idx_approval_result (approval_result),
    INDEX idx_approval_step (approval_step),
    INDEX idx_process_time (process_time),
    FOREIGN KEY (workflow_instance_id) REFERENCES t_workflow_instance(workflow_instance_id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES t_workflow_task(task_id) ON DELETE SET NULL,
    FOREIGN KEY (document_id) REFERENCES t_document(document_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批记录表';

-- 8. 会议室信息表
DROP TABLE IF EXISTS t_meeting_room;
CREATE TABLE t_meeting_room (
    meeting_room_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '会议室ID',
    room_code VARCHAR(50) NOT NULL UNIQUE COMMENT '会议室编码',
    room_name VARCHAR(100) NOT NULL COMMENT '会议室名称',
    room_type VARCHAR(30) NOT NULL COMMENT '会议室类型(SMALL-小型,MEDIUM-中型,LARGE-大型,VIDEO-视频)',
    building_id BIGINT COMMENT '楼宇ID',
    building_name VARCHAR(100) COMMENT '楼宇名称',
    floor_number INT COMMENT '楼层号',
    room_number VARCHAR(20) COMMENT '房间号',
    capacity INT NOT NULL COMMENT '容纳人数',
    area_size DECIMAL(8,2) COMMENT '面积(平方米)',
    room_status VARCHAR(20) DEFAULT 'AVAILABLE' COMMENT '会议室状态(AVAILABLE-可用,MAINTENANCE-维护中,OCCUPIED-使用中)',
    facilities JSON COMMENT '设施配置(JSON格式)',
    equipment_list JSON COMMENT '设备清单(JSON格式)',
    room_image_url VARCHAR(500) COMMENT '会议室图片URL',
    layout_image_url VARCHAR(500) COMMENT '布局图URL',
    description TEXT COMMENT '会议室描述',
    location_description VARCHAR(200) COMMENT '位置描述',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    is_public TINYINT DEFAULT 1 COMMENT '是否公开(0-否,1-是)',
    booking_rule VARCHAR(50) DEFAULT 'FIRST_COME' COMMENT '预约规则(FIRST_COME-先到先得,APPROVAL-需要审批)',
    advance_booking_days INT DEFAULT 30 COMMENT '提前预约天数',
    max_booking_hours INT DEFAULT 8 COMMENT '最大预约小时数',
    auto_confirm TINYINT DEFAULT 1 COMMENT '是否自动确认(0-否,1-是)',
    cancel_policy VARCHAR(20) DEFAULT 'FREE' COMMENT '取消政策(FREE-免费,PENALTY-罚金)',
    cancel_deadline_hours INT DEFAULT 2 COMMENT '取消提前小时数',
    penalty_rate DECIMAL(5,2) DEFAULT 0.00 COMMENT '罚金比例(%)',
    manager_id BIGINT COMMENT '管理员ID',
    manager_name VARCHAR(50) COMMENT '管理员姓名',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_room_code (room_code),
    INDEX idx_room_type (room_type),
    INDEX idx_room_status (room_status),
    INDEX idx_building_id (building_id),
    INDEX idx_floor_number (floor_number),
    INDEX idx_capacity (capacity),
    INDEX idx_is_public (is_public),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会议室信息表';

-- 9. 会议预约表
DROP TABLE IF EXISTS t_meeting_booking;
CREATE TABLE t_meeting_booking (
    meeting_booking_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '会议预约ID',
    booking_code VARCHAR(50) NOT NULL UNIQUE COMMENT '预约编码',
    meeting_title VARCHAR(200) NOT NULL COMMENT '会议主题',
    meeting_type VARCHAR(30) DEFAULT 'REGULAR' COMMENT '会议类型(REGULAR-常规,URGENT-紧急,VIDEO-视频,TRAINING-培训)',
    meeting_room_id BIGINT NOT NULL COMMENT '会议室ID',
    meeting_room_name VARCHAR(100) NOT NULL COMMENT '会议室名称',
    organizer_id BIGINT NOT NULL COMMENT '组织人ID',
    organizer_name VARCHAR(50) NOT NULL COMMENT '组织人姓名',
    organizer_dept_id BIGINT COMMENT '组织部门ID',
    organizer_dept_name VARCHAR(100) COMMENT '组织部门名称',
    meeting_date DATE NOT NULL COMMENT '会议日期',
    start_time DATETIME NOT NULL COMMENT '开始时间',
    end_time DATETIME NOT NULL COMMENT '结束时间',
    duration_minutes INT NOT NULL COMMENT '会议时长(分钟)',
    attendee_count INT DEFAULT 0 COMMENT '参会人数',
    is_recurring TINYINT DEFAULT 0 COMMENT '是否重复会议(0-否,1-是)',
    recurring_pattern JSON COMMENT '重复模式(JSON格式)',
    booking_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '预约状态(PENDING-待确认,CONFIRMED-已确认,CANCELLED-已取消,COMPLETED-已完成)',
    approval_status VARCHAR(20) COMMENT '审批状态(NONE-无需审批,PENDING-待审批,APPROVED-已审批,REJECTED-已拒绝)',
    approver_id BIGINT COMMENT '审批人ID',
    approver_name VARCHAR(50) COMMENT '审批人姓名',
    approval_time DATETIME COMMENT '审批时间',
    approval_comment TEXT COMMENT '审批意见',
    meeting_description TEXT COMMENT '会议描述',
    agenda TEXT COMMENT '会议议程',
    meeting_materials JSON COMMENT '会议材料(JSON格式)',
    attendee_list JSON COMMENT '参会人员列表(JSON格式)',
    external_attendees JSON COMMENT '外部参会人员(JSON格式)',
    catering_required TINYINT DEFAULT 0 COMMENT '是否需要餐饮(0-否,1-是)',
    catering_details JSON COMMENT '餐饮详情(JSON格式)',
    equipment_required JSON COMMENT '所需设备(JSON格式)',
    special_requirements TEXT COMMENT '特殊要求',
    cost_center VARCHAR(50) COMMENT '成本中心',
    budget_amount DECIMAL(10,2) COMMENT '预算金额',
    actual_cost DECIMAL(10,2) COMMENT '实际费用',
    cancel_reason TEXT COMMENT '取消原因',
    cancel_time DATETIME COMMENT '取消时间',
    feedback_rating INT COMMENT '反馈评分(1-5)',
    feedback_comment TEXT COMMENT '反馈意见',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_booking_code (booking_code),
    INDEX idx_meeting_room_id (meeting_room_id),
    INDEX idx_organizer_id (organizer_id),
    INDEX idx_meeting_date (meeting_date),
    INDEX idx_start_time (start_time),
    INDEX idx_end_time (end_time),
    INDEX idx_booking_status (booking_status),
    INDEX idx_approval_status (approval_status),
    INDEX idx_create_time (create_time),
    FOREIGN KEY (meeting_room_id) REFERENCES t_meeting_room(meeting_room_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会议预约表';

-- 10. 会议记录表
DROP TABLE IF EXISTS t_meeting_record;
CREATE TABLE t_meeting_record (
    meeting_record_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '会议记录ID',
    meeting_booking_id BIGINT NOT NULL COMMENT '会议预约ID',
    actual_start_time DATETIME COMMENT '实际开始时间',
    actual_end_time DATETIME COMMENT '实际结束时间',
    actual_duration_minutes INT COMMENT '实际时长(分钟)',
    actual_attendee_count INT DEFAULT 0 COMMENT '实际参会人数',
    meeting_summary TEXT COMMENT '会议总结',
    meeting_decisions TEXT COMMENT '会议决议',
    action_items JSON COMMENT '行动项(JSON格式)',
    next_meeting_info JSON COMMENT '下次会议信息(JSON格式)',
    meeting_minutes LONGTEXT COMMENT '会议纪要',
    recording_file_url VARCHAR(500) COMMENT '录音文件URL',
    transcript_text LONGTEXT COMMENT '会议转录文本',
    presentation_files JSON COMMENT '演示文稿(JSON格式)',
    photos JSON COMMENT '会议照片(JSON格式)',
    follow_up_tasks JSON COMMENT '后续任务(JSON格式)',
    expense_records JSON COMMENT '费用记录(JSON格式)',
    satisfaction_rating INT COMMENT '满意度评分(1-5)',
    improvement_suggestions TEXT COMMENT '改进建议',
    recorder_id BIGINT COMMENT '记录人ID',
    recorder_name VARCHAR(50) COMMENT '记录人姓名',
    is_published TINYINT DEFAULT 0 COMMENT '是否已发布(0-否,1-是)',
    publish_time DATETIME COMMENT '发布时间',
    distribution_list JSON COMMENT '分发列表(JSON格式)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_user_id BIGINT COMMENT '创建人ID',
    update_user_id BIGINT COMMENT '更新人ID',
    deleted_flag TINYINT DEFAULT 0 COMMENT '删除标记(0-正常,1-删除)',
    version INT DEFAULT 1 COMMENT '版本号',

    INDEX idx_meeting_booking_id (meeting_booking_id),
    INDEX idx_actual_start_time (actual_start_time),
    INDEX idx_actual_end_time (actual_end_time),
    INDEX idx_is_published (is_published),
    INDEX idx_publish_time (publish_time),
    INDEX idx_create_time (create_time),
    FOREIGN KEY (meeting_booking_id) REFERENCES t_meeting_booking(meeting_booking_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会议记录表';

-- 添加外键约束
ALTER TABLE t_document ADD CONSTRAINT fk_document_parent FOREIGN KEY (parent_document_id) REFERENCES t_document(document_id) ON DELETE SET NULL;