-- 创建支付记录表
CREATE TABLE `t_consume_payment_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `payment_id` VARCHAR(64) NOT NULL COMMENT '支付ID（业务唯一标识）',
    `payment_type` VARCHAR(32) NOT NULL COMMENT '支付类型（WECHAT, ALIPAY, ALIPAY_APP, WECHAT_NATIVE等）',
    `amount` DECIMAL(10,2) NOT NULL COMMENT '支付金额',
    `subject` VARCHAR(255) NOT NULL COMMENT '支付主题/商品名称',
    `body` VARCHAR(500) COMMENT '支付描述/商品详情',
    `consume_record_id` BIGINT COMMENT '关联的消费记录ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '支付状态（PENDING, SUCCESS, FAILED, CLOSED, REFUNDED）',
    `third_party_transaction_id` VARCHAR(128) COMMENT '第三方交易ID（微信trade_no, 支付宝trade_no等）',
    `prepay_id` VARCHAR(128) COMMENT '预支付ID（微信prepay_id）',
    `qr_code` TEXT COMMENT '二维码URL（Native支付）',
    `form_data` TEXT COMMENT '支付表单数据（网页支付）',
    `order_string` TEXT COMMENT '订单字符串（APP支付）',
    `payment_time` DATETIME COMMENT '支付时间',
    `payment_channel` VARCHAR(32) COMMENT '支付渠道（WEB, APP, SCAN_CODE等）',
    `payment_ip` VARCHAR(45) COMMENT '支付IP地址',
    `extend_info` TEXT COMMENT '扩展信息（JSON格式）',
    `remark` VARCHAR(500) COMMENT '备注信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_id` (`payment_id`),
    KEY `idx_consume_record_id` (`consume_record_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_payment_time` (`payment_time`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_third_party_transaction_id` (`third_party_transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付记录表';

-- 创建退款记录表
CREATE TABLE `t_consume_refund_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `refund_id` VARCHAR(64) NOT NULL COMMENT '退款ID（业务唯一标识）',
    `payment_id` VARCHAR(64) NOT NULL COMMENT '关联的支付ID',
    `consume_record_id` BIGINT COMMENT '关联的消费记录ID',
    `refund_amount` DECIMAL(10,2) NOT NULL COMMENT '退款金额',
    `reason` VARCHAR(500) COMMENT '退款原因',
    `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '退款状态（PENDING, SUCCESS, FAILED, CANCELLED）',
    `third_party_refund_id` VARCHAR(128) COMMENT '第三方退款ID（微信refund_id, 支付宝refund_no等）',
    `refund_time` DATETIME COMMENT '退款时间',
    `refund_channel` VARCHAR(32) COMMENT '退款渠道（同支付渠道）',
    `refund_way` VARCHAR(32) COMMENT '退款方式（ORIGINAL, BALANCE, BANK_CARD等）',
    `refund_fee` DECIMAL(10,2) COMMENT '退款手续费',
    `apply_time` DATETIME COMMENT '退款申请时间',
    `process_time` DATETIME COMMENT '退款处理时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `operator_name` VARCHAR(100) COMMENT '操作人姓名',
    `extend_info` TEXT COMMENT '扩展信息（JSON格式）',
    `remark` VARCHAR(500) COMMENT '备注信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_refund_id` (`refund_id`),
    KEY `idx_payment_id` (`payment_id`),
    KEY `idx_consume_record_id` (`consume_record_id`),
    KEY `idx_status` (`status`),
    KEY `idx_refund_time` (`refund_time`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_third_party_refund_id` (`third_party_refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款记录表';

-- 创建产品分类表
CREATE TABLE `t_product_category` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `category_code` VARCHAR(32) NOT NULL COMMENT '分类编码',
    `category_name` VARCHAR(100) NOT NULL COMMENT '分类名称',
    `description` VARCHAR(500) COMMENT '分类描述',
    `parent_id` BIGINT COMMENT '父分类ID',
    `level` INT NOT NULL DEFAULT 1 COMMENT '分类层级',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
    `icon` VARCHAR(255) COMMENT '分类图标',
    `image` VARCHAR(500) COMMENT '分类图片',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（ACTIVE:启用, INACTIVE:禁用）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_category_code` (`category_code`),
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_level` (`level`),
    KEY `idx_status` (`status`),
    KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品分类表';

-- 创建产品表
CREATE TABLE `t_product` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `product_code` VARCHAR(64) NOT NULL COMMENT '产品编码',
    `product_name` VARCHAR(200) NOT NULL COMMENT '产品名称',
    `category_id` BIGINT COMMENT '分类ID',
    `description` TEXT COMMENT '产品描述',
    `price` DECIMAL(10,2) NOT NULL COMMENT '产品价格',
    `cost_price` DECIMAL(10,2) COMMENT '成本价格',
    `barcode` VARCHAR(64) COMMENT '产品条码',
    `qr_code` VARCHAR(255) COMMENT '产品二维码',
    `image` VARCHAR(500) COMMENT '产品图片',
    `images` TEXT COMMENT '产品图片列表（JSON格式）',
    `stock` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
    `min_stock` INT NOT NULL DEFAULT 0 COMMENT '最低库存预警',
    `unit` VARCHAR(20) COMMENT '计量单位',
    `specifications` VARCHAR(500) COMMENT '产品规格',
    `brand` VARCHAR(100) COMMENT '品牌',
    `supplier` VARCHAR(200) COMMENT '供应商',
    `tags` VARCHAR(500) COMMENT '产品标签',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（ACTIVE:上架, INACTIVE:下架, OUT_OF_STOCK:缺货）',
    `is_recommend` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否推荐',
    `is_hot` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否热销',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
    `sales_count` INT NOT NULL DEFAULT 0 COMMENT '销售数量',
    `view_count` INT NOT NULL DEFAULT 0 COMMENT '浏览次数',
    `extend_info` TEXT COMMENT '扩展信息（JSON格式）',
    `remark` VARCHAR(500) COMMENT '备注信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_code` (`product_code`),
    UNIQUE KEY `uk_barcode` (`barcode`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_status` (`status`),
    KEY `idx_price` (`price`),
    KEY `idx_stock` (`stock`),
    KEY `idx_is_recommend` (`is_recommend`),
    KEY `idx_is_hot` (`is_hot`),
    KEY `idx_sales_count` (`sales_count`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品表';

-- 创建菜单分类表
CREATE TABLE `t_menu_category` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `category_code` VARCHAR(32) NOT NULL COMMENT '分类编码',
    `category_name` VARCHAR(100) NOT NULL COMMENT '分类名称',
    `description` VARCHAR(500) COMMENT '分类描述',
    `icon` VARCHAR(255) COMMENT '分类图标',
    `image` VARCHAR(500) COMMENT '分类图片',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（ACTIVE:启用, INACTIVE:禁用）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_category_code` (`category_code`),
    KEY `idx_status` (`status`),
    KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜单分类表';

-- 创建菜单表
CREATE TABLE `t_menu` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `menu_code` VARCHAR(64) NOT NULL COMMENT '菜单编码',
    `menu_name` VARCHAR(200) NOT NULL COMMENT '菜单名称',
    `category_id` BIGINT COMMENT '分类ID',
    `description` TEXT COMMENT '菜单描述',
    `price` DECIMAL(10,2) NOT NULL COMMENT '价格',
    `original_price` DECIMAL(10,2) COMMENT '原价',
    `image` VARCHAR(500) COMMENT '菜单图片',
    `images` TEXT COMMENT '图片列表（JSON格式）',
    `stock` INT NOT NULL DEFAULT -1 COMMENT '库存数量（-1表示无限）',
    `min_stock` INT NOT NULL DEFAULT 0 COMMENT '最低库存预警',
    `sales_count` INT NOT NULL DEFAULT 0 COMMENT '销售数量',
    `view_count` INT NOT NULL DEFAULT 0 COMMENT '浏览次数',
    `rating` DECIMAL(3,2) DEFAULT 0.00 COMMENT '评分',
    `rating_count` INT NOT NULL DEFAULT 0 COMMENT '评分人数',
    `spicy_level` INT DEFAULT 0 COMMENT '辣度等级（0-5）',
    `cooking_time` INT COMMENT '烹饪时间（分钟）',
    `ingredients` TEXT COMMENT '主要食材',
    `allergens` VARCHAR(500) COMMENT '过敏原',
    `nutrition_info` TEXT COMMENT '营养信息（JSON格式）',
    `tags` VARCHAR(500) COMMENT '标签',
    `status` VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' COMMENT '状态（AVAILABLE:可售, UNAVAILABLE:不可售, OUT_OF_STOCK:售罄）',
    `is_recommend` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否推荐',
    `is_special` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否特色',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
    `extend_info` TEXT COMMENT '扩展信息（JSON格式）',
    `remark` VARCHAR(500) COMMENT '备注信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_menu_code` (`menu_code`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_status` (`status`),
    KEY `idx_price` (`price`),
    KEY `idx_stock` (`stock`),
    KEY `idx_is_recommend` (`is_recommend`),
    KEY `idx_is_special` (`is_special`),
    KEY `idx_sales_count` (`sales_count`),
    KEY `idx_rating` (`rating`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜单表';

-- 创建点餐订单表
CREATE TABLE `t_ordering` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `table_no` VARCHAR(20) COMMENT '桌号',
    `order_type` VARCHAR(32) NOT NULL COMMENT '订单类型（DINE_IN:堂食, TAKEAWAY:外带, DELIVERY:配送）',
    `total_amount` DECIMAL(10,2) NOT NULL COMMENT '总金额',
    `discount_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '优惠金额',
    `final_amount` DECIMAL(10,2) NOT NULL COMMENT '实付金额',
    `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '订单状态（PENDING:待处理, PROCESSING:处理中, COMPLETED:已完成, CANCELLED:已取消）',
    `payment_status` VARCHAR(32) DEFAULT 'UNPAID' COMMENT '支付状态（UNPAID:未支付, PAID:已支付, REFUNDED:已退款）',
    `cancel_reason` VARCHAR(500) COMMENT '取消原因',
    `delivery_address` VARCHAR(500) COMMENT '配送地址',
    `contact_phone` VARCHAR(20) COMMENT '联系电话',
    `contact_name` VARCHAR(100) COMMENT '联系人姓名',
    `estimated_time` INT COMMENT '预计完成时间（分钟）',
    `actual_time` INT COMMENT '实际完成时间（分钟）',
    `extend_info` TEXT COMMENT '扩展信息（JSON格式）',
    `remark` VARCHAR(500) COMMENT '备注信息',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0:未删除, 1:已删除）',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_payment_status` (`payment_status`),
    KEY `idx_order_type` (`order_type`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='点餐订单表';

-- 创建点餐订单项表
CREATE TABLE `t_ordering_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `ordering_id` BIGINT NOT NULL COMMENT '订单ID',
    `menu_id` BIGINT NOT NULL COMMENT '菜单ID',
    `menu_name` VARCHAR(200) NOT NULL COMMENT '菜单名称',
    `menu_price` DECIMAL(10,2) NOT NULL COMMENT '菜单单价',
    `quantity` INT NOT NULL DEFAULT 1 COMMENT '数量',
    `subtotal` DECIMAL(10,2) NOT NULL COMMENT '小计金额',
    `specifications` VARCHAR(500) COMMENT '规格要求',
    `special_instructions` VARCHAR(500) COMMENT '特殊要求',
    `status` VARCHAR(32) DEFAULT 'NORMAL' COMMENT '状态（NORMAL:正常, CANCELLED:已取消）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ordering_id` (`ordering_id`),
    KEY `idx_menu_id` (`menu_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='点餐订单项表';

-- 创建用户优惠券表
CREATE TABLE `t_user_coupon` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `coupon_id` BIGINT NOT NULL COMMENT '优惠券ID',
    `coupon_code` VARCHAR(64) NOT NULL COMMENT '优惠券编码',
    `coupon_name` VARCHAR(200) NOT NULL COMMENT '优惠券名称',
    `coupon_type` VARCHAR(32) NOT NULL COMMENT '优惠券类型（DISCOUNT:折扣, CASH:现金）',
    `discount_amount` DECIMAL(10,2) COMMENT '优惠金额',
    `discount_rate` DECIMAL(5,4) COMMENT '折扣率',
    `min_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '最低消费金额',
    `max_discount` DECIMAL(10,2) COMMENT '最大优惠金额',
    `description` VARCHAR(500) COMMENT '使用说明',
    `valid_from` DATETIME NOT NULL COMMENT '有效期开始时间',
    `valid_until` DATETIME NOT NULL COMMENT '有效期结束时间',
    `status` VARCHAR(32) NOT NULL DEFAULT 'UNUSED' COMMENT '状态（UNUSED:未使用, USED:已使用, EXPIRED:已过期）',
    `used_time` DATETIME COMMENT '使用时间',
    `used_order_id` BIGINT COMMENT '使用的订单ID',
    `extend_info` TEXT COMMENT '扩展信息（JSON格式）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_coupon_code` (`coupon_code`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_coupon_id` (`coupon_id`),
    KEY `idx_status` (`status`),
    KEY `idx_valid_from` (`valid_from`),
    KEY `idx_valid_until` (`valid_until`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户优惠券表';

-- 插入基础数据

-- 插入默认产品分类
INSERT INTO `t_product_category` (`category_code`, `category_name`, `description`, `level`, `sort_order`, `status`) VALUES
('FOOD', '食品饮料', '各类食品和饮料', 1, 1, 'ACTIVE'),
('DAILY', '日用品', '日常生活用品', 1, 2, 'ACTIVE'),
('ELECTRONIC', '电子产品', '电子设备和配件', 1, 3, 'ACTIVE'),
('CLOTHING', '服装鞋帽', '服装、鞋子、帽子等', 1, 4, 'ACTIVE'),
('BOOKS', '图书文具', '书籍和文具用品', 1, 5, 'ACTIVE'),
('OTHER', '其他', '其他商品类别', 1, 99, 'ACTIVE');

-- 插入默认菜单分类
INSERT INTO `t_menu_category` (`category_code`, `category_name`, `description`, `sort_order`, `status`) VALUES
('HOT_DISH', '热菜', '各种炒菜、炖菜等热菜', 1, 'ACTIVE'),
('COLD_DISH', '凉菜', '各种凉菜、沙拉等', 2, 'ACTIVE'),
('SOUP', '汤类', '各种汤品', 3, 'ACTIVE'),
('RICE_NOODLE', '米饭面食', '米饭、面条、饺子等主食', 4, 'ACTIVE'),
('DRINK', '饮品', '各种饮料、茶水、咖啡等', 5, 'ACTIVE'),
('DESSERT', '甜点', '各种甜点、水果等', 6, 'ACTIVE'),
('SET_MEAL', '套餐', '各种套餐组合', 7, 'ACTIVE');