-- =====================================================
-- IOE-DREAM Flyway 迁移脚本
-- 版本: V2.1.7
-- 描述: 批量补齐缺口表（第3批：访客/消费/门禁/考勤/工作流/审批）
-- =====================================================

CREATE TABLE IF NOT EXISTS t_visitor_area (area_id BIGINT AUTO_INCREMENT PRIMARY KEY, area_name VARCHAR(100) NOT NULL, area_code VARCHAR(50), parent_id BIGINT DEFAULT 0, area_type VARCHAR(50), status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_visitor_driver (driver_id BIGINT AUTO_INCREMENT PRIMARY KEY, driver_name VARCHAR(100) NOT NULL, phone VARCHAR(20), id_card VARCHAR(20), license_no VARCHAR(50), status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_visitor_vehicle (vehicle_id BIGINT AUTO_INCREMENT PRIMARY KEY, plate_no VARCHAR(20) NOT NULL, vehicle_type VARCHAR(50), vehicle_color VARCHAR(20), driver_id BIGINT, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_visitor_electronic_pass (pass_id BIGINT AUTO_INCREMENT PRIMARY KEY, pass_no VARCHAR(50) NOT NULL, visitor_id BIGINT NOT NULL, appointment_id BIGINT, qr_code VARCHAR(500), valid_start DATETIME, valid_end DATETIME, status TINYINT DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_pass_no (pass_no, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_access_area_ext (ext_id BIGINT AUTO_INCREMENT PRIMARY KEY, area_id BIGINT NOT NULL, access_level TINYINT DEFAULT 1, require_face TINYINT DEFAULT 0, require_card TINYINT DEFAULT 1, require_password TINYINT DEFAULT 0, time_rule_id BIGINT, config_json TEXT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_area_id (area_id, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_consume_area_ext (ext_id BIGINT AUTO_INCREMENT PRIMARY KEY, area_id BIGINT NOT NULL, consume_type VARCHAR(50), price_rule_id BIGINT, subsidy_rule_id BIGINT, config_json TEXT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_area_id (area_id, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_consume_payment_record (record_id BIGINT AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(50) NOT NULL, user_id BIGINT NOT NULL, amount DECIMAL(10,2) NOT NULL, payment_method VARCHAR(50), payment_status TINYINT DEFAULT 0, payment_time DATETIME, trade_no VARCHAR(100), remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_order_no (order_no, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_consume_payment_refund_record (refund_id BIGINT AUTO_INCREMENT PRIMARY KEY, payment_record_id BIGINT NOT NULL, refund_no VARCHAR(50) NOT NULL, refund_amount DECIMAL(10,2) NOT NULL, refund_reason VARCHAR(500), refund_status TINYINT DEFAULT 0, refund_time DATETIME, operator_id BIGINT, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_refund_no (refund_no, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_consume_qrcode (qrcode_id BIGINT AUTO_INCREMENT PRIMARY KEY, qrcode_no VARCHAR(50) NOT NULL, qrcode_type VARCHAR(50), qrcode_content VARCHAR(500), user_id BIGINT, valid_start DATETIME, valid_end DATETIME, status TINYINT DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_qrcode_no (qrcode_no, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_consume_report_template (template_id BIGINT AUTO_INCREMENT PRIMARY KEY, template_code VARCHAR(50) NOT NULL, template_name VARCHAR(100) NOT NULL, template_type VARCHAR(50), template_config TEXT, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_template_code (template_code, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_area_person (relation_id BIGINT AUTO_INCREMENT PRIMARY KEY, area_id BIGINT NOT NULL, person_id BIGINT NOT NULL, person_type VARCHAR(50), permission_type VARCHAR(50), valid_start DATETIME, valid_end DATETIME, status TINYINT DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_area_person (area_id, person_id, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_audit_archive (archive_id BIGINT AUTO_INCREMENT PRIMARY KEY, archive_date DATE NOT NULL, archive_type VARCHAR(50), record_count BIGINT DEFAULT 0, file_path VARCHAR(500), file_size BIGINT, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_config_change_approval (approval_id BIGINT AUTO_INCREMENT PRIMARY KEY, change_id BIGINT NOT NULL, approver_id BIGINT NOT NULL, approval_status TINYINT DEFAULT 0, approval_time DATETIME, approval_remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_config_change_rollback (rollback_id BIGINT AUTO_INCREMENT PRIMARY KEY, change_id BIGINT NOT NULL, rollback_reason VARCHAR(500), rollback_status TINYINT DEFAULT 0, rollback_time DATETIME, operator_id BIGINT, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'V2.1.7 Flyway Batch3 完成' AS status;
