-- =====================================================
-- IOE-DREAM Flyway 迁移脚本
-- 版本: V2.1.8
-- 描述: 批量补齐缺口表（第4批：工作流/审批/考勤/门禁申请）
-- =====================================================

CREATE TABLE IF NOT EXISTS t_common_workflow_definition (definition_id BIGINT AUTO_INCREMENT PRIMARY KEY, workflow_code VARCHAR(50) NOT NULL, workflow_name VARCHAR(100) NOT NULL, workflow_type VARCHAR(50), definition_json TEXT, version INT DEFAULT 1, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, create_user_id BIGINT, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_workflow_code_version (workflow_code, version, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_workflow_instance (instance_id BIGINT AUTO_INCREMENT PRIMARY KEY, definition_id BIGINT NOT NULL, business_key VARCHAR(100), business_type VARCHAR(50), initiator_id BIGINT NOT NULL, current_node VARCHAR(100), instance_status TINYINT DEFAULT 1, start_time DATETIME, end_time DATETIME, variables_json TEXT, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_workflow_task (task_id BIGINT AUTO_INCREMENT PRIMARY KEY, instance_id BIGINT NOT NULL, task_name VARCHAR(100), task_node VARCHAR(100), assignee_id BIGINT, task_status TINYINT DEFAULT 1, action VARCHAR(50), comment VARCHAR(500), start_time DATETIME, end_time DATETIME, due_time DATETIME, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_approval_config (config_id BIGINT AUTO_INCREMENT PRIMARY KEY, approval_type VARCHAR(50) NOT NULL, config_name VARCHAR(100) NOT NULL, config_json TEXT, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_approval_node_config (node_id BIGINT AUTO_INCREMENT PRIMARY KEY, config_id BIGINT NOT NULL, node_name VARCHAR(100) NOT NULL, node_type VARCHAR(50), approver_type VARCHAR(50), approver_ids VARCHAR(500), node_order INT DEFAULT 0, config_json TEXT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_approval_template (template_id BIGINT AUTO_INCREMENT PRIMARY KEY, template_code VARCHAR(50) NOT NULL, template_name VARCHAR(100) NOT NULL, template_type VARCHAR(50), form_config TEXT, flow_config TEXT, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_template_code (template_code, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_common_approval_statistics (stat_id BIGINT AUTO_INCREMENT PRIMARY KEY, stat_date DATE NOT NULL, approval_type VARCHAR(50), total_count INT DEFAULT 0, pending_count INT DEFAULT 0, approved_count INT DEFAULT 0, rejected_count INT DEFAULT 0, avg_process_time BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS access_approval_process (process_id BIGINT AUTO_INCREMENT PRIMARY KEY, apply_id BIGINT NOT NULL, approver_id BIGINT NOT NULL, approval_order INT DEFAULT 0, approval_status TINYINT DEFAULT 0, approval_time DATETIME, approval_remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS access_permission_apply (apply_id BIGINT AUTO_INCREMENT PRIMARY KEY, applicant_id BIGINT NOT NULL, apply_type VARCHAR(50), area_ids VARCHAR(500), valid_start DATETIME, valid_end DATETIME, apply_reason VARCHAR(500), apply_status TINYINT DEFAULT 0, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS visitor_appointment (appointment_id BIGINT AUTO_INCREMENT PRIMARY KEY, visitor_name VARCHAR(100) NOT NULL, visitor_phone VARCHAR(20), visitor_company VARCHAR(200), host_id BIGINT, host_name VARCHAR(100), visit_purpose VARCHAR(500), visit_start DATETIME, visit_end DATETIME, area_ids VARCHAR(500), appointment_status TINYINT DEFAULT 0, check_in_time DATETIME, check_out_time DATETIME, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_leave (leave_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, leave_type VARCHAR(50) NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, duration DECIMAL(10,2), reason VARCHAR(500), approval_status TINYINT DEFAULT 0, approver_id BIGINT, approval_time DATETIME, approval_remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_overtime (overtime_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, overtime_type VARCHAR(50), start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, duration DECIMAL(10,2), reason VARCHAR(500), approval_status TINYINT DEFAULT 0, approver_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_shift (shift_id BIGINT AUTO_INCREMENT PRIMARY KEY, shift_name VARCHAR(100) NOT NULL, shift_code VARCHAR(50), work_start TIME, work_end TIME, break_start TIME, break_end TIME, work_hours DECIMAL(4,2), is_flexible TINYINT DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_shift_code (shift_code, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_supplement (supplement_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, supplement_date DATE NOT NULL, supplement_type VARCHAR(50), supplement_time DATETIME, reason VARCHAR(500), approval_status TINYINT DEFAULT 0, approver_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_travel (travel_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, destination VARCHAR(200), start_date DATE NOT NULL, end_date DATE NOT NULL, days INT, reason VARCHAR(500), approval_status TINYINT DEFAULT 0, approver_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consume_product (product_id BIGINT AUTO_INCREMENT PRIMARY KEY, product_code VARCHAR(50) NOT NULL, product_name VARCHAR(200) NOT NULL, category_id BIGINT, price DECIMAL(10,2) NOT NULL, unit VARCHAR(20), stock INT DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_product_code (product_code, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consume_subsidy_issue_record (record_id BIGINT AUTO_INCREMENT PRIMARY KEY, subsidy_rule_id BIGINT, user_id BIGINT NOT NULL, amount DECIMAL(10,2) NOT NULL, issue_date DATE NOT NULL, issue_type VARCHAR(50), status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consume_transaction (transaction_id BIGINT AUTO_INCREMENT PRIMARY KEY, transaction_no VARCHAR(50) NOT NULL, user_id BIGINT NOT NULL, account_id BIGINT, transaction_type VARCHAR(50) NOT NULL, amount DECIMAL(10,2) NOT NULL, balance_before DECIMAL(10,2), balance_after DECIMAL(10,2), device_id BIGINT, area_id BIGINT, status TINYINT DEFAULT 1, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_transaction_no (transaction_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_record (record_id BIGINT AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(50) NOT NULL, user_id BIGINT NOT NULL, amount DECIMAL(10,2) NOT NULL, payment_method VARCHAR(50), payment_status TINYINT DEFAULT 0, payment_time DATETIME, trade_no VARCHAR(100), remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0, UNIQUE KEY uk_order_no (order_no, deleted_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refund_application (application_id BIGINT AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(50) NOT NULL, user_id BIGINT NOT NULL, refund_amount DECIMAL(10,2) NOT NULL, refund_reason VARCHAR(500), refund_status TINYINT DEFAULT 0, approver_id BIGINT, approval_time DATETIME, refund_time DATETIME, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reimbursement_application (application_id BIGINT AUTO_INCREMENT PRIMARY KEY, applicant_id BIGINT NOT NULL, reimbursement_type VARCHAR(50), amount DECIMAL(10,2) NOT NULL, description VARCHAR(500), attachments TEXT, approval_status TINYINT DEFAULT 0, approver_id BIGINT, approval_time DATETIME, payment_status TINYINT DEFAULT 0, payment_time DATETIME, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_flag TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'V2.1.8 Flyway Batch4 完成' AS status;
