package net.lab1024.sa.attendance.engine.model;

import lombok.Data;
import lombok.Builder;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * 排班结果模型
 * <p>
 * 智能排班引擎的输出结果
 * 严格遵循CLAUDE.md全局架构规范
 * </p>
 *
 * @author IOE-DREAM架构团队
 * @version 1.0.0
 * @since 2025-12-16
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ScheduleResult {

    /**
     * 排班结果ID
     */
    private Long resultId;

    /**
     * 排班计划ID
     */
    private Long planId;

    /**
     * 排班状态：SUCCESS-成功 FAILED-失败 PARTIAL-部分成功
     */
    private String status;

    /**
     * 排班消息
     */
    private String message;

    /**
     * 生成的排班记录列表
     */
    private List<ScheduleRecord> scheduleRecords;

    /**
     * 排班冲突列表
     */
    private List<ScheduleConflict> conflicts;

    /**
     * 排班统计信息
     */
    private ScheduleStatistics statistics;

    /**
     * 排班执行时间（毫秒）
     */
    private Long executionTime;

    /**
     * 使用的算法
     */
    private String algorithmUsed;

    /**
     * 优化指标
     */
    private Map<String, Object> optimizationMetrics;

    /**
     * 排班质量评分
     */
    private Double qualityScore;

    /**
     * 是否需要人工审核
     */
    private Boolean needsReview;

    /**
     * 推荐的改进建议
     */
    private List<String> recommendations;

    /**
     * 排班完成时间
     */
    private LocalDateTime completedAt;

    /**
     * 扩展属性
     */
    private Map<String, Object> extendedAttributes;

    /**
     * 排班记录内部类
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ScheduleRecord {
        /**
         * 记录ID
         */
        private Long recordId;

        /**
         * 用户ID
         */
        private Long userId;

        /**
         * 部门ID
         */
        private Long departmentId;

        /**
         * 班次ID
         */
        private Long shiftId;

        /**
         * 排班日期
         */
        private String scheduleDate;

        /**
         * 工作开始时间
         */
        private String startTime;

        /**
         * 工作结束时间
         */
        private String endTime;

        /**
         * 工作地点
         */
        private String workLocation;

        /**
         * 排班优先级
         */
        private Integer priority;

        /**
         * 是否自动生成
         */
        private Boolean autoGenerated;

        /**
         * 排班来源
         */
        private String source;
    }

    /**
     * 排班冲突内部类
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ScheduleConflict {
        /**
         * 冲突ID
         */
        private String conflictId;

        /**
         * 冲突类型
         */
        private String conflictType;

        /**
         * 冲突描述
         */
        private String description;

        /**
         * 冲突严重程度：LOW-低 MEDIUM-中 HIGH-高 CRITICAL-严重
         */
        private String severity;

        /**
         * 涉及的用户列表
         */
        private List<Long> affectedUsers;

        /**
         * 冲突日期
         */
        private String conflictDate;

        /**
         * 冲突时间段
         */
        private List<String> timeSlots;

        /**
         * 建议解决方案
         */
        private List<String> suggestedSolutions;
    }

    /**
     * 排班统计信息内部类
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ScheduleStatistics {
        /**
         * 总排班人数
         */
        private Integer totalUsers;

        /**
         * 总排班天数
         */
        private Integer totalDays;

        /**
         * 总排班记录数
         */
        private Integer totalRecords;

        /**
         * 平均每人排班天数
         */
        private Double averageDaysPerUser;

        /**
         * 工作负载均衡度
         */
        private Double workloadBalance;

        /**
         * 班次覆盖率
         */
        private Double shiftCoverage;

        /**
         * 约束满足率
         */
        private Double constraintSatisfaction;

        /**
         * 成本节约率
         */
        private Double costSaving;
    }
}