package net.lab1024.sa.attendance.engine.model;

import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * 排班记录模型
 * <p>
 * 排班记录的基础数据结构
 * 严格遵循CLAUDE.md全局架构规范
 * </p>
 *
 * @author IOE-DREAM架构团队
 * @version 1.0.0
 * @since 2025-12-16
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ScheduleRecord {

    /**
     * 记录ID
     */
    private Long recordId;

    /**
     * 员工ID
     */
    private Long employeeId;

    /**
     * 员工姓名
     */
    private String employeeName;

    /**
     * 部门ID
     */
    private Long departmentId;

    /**
     * 班次ID
     */
    private Long shiftId;

    /**
     * 排班日期
     */
    private String scheduleDate;

    /**
     * 工作开始时间
     */
    private LocalDateTime startTime;

    /**
     * 工作结束时间
     */
    private LocalDateTime endTime;

    /**
     * 工作地点
     */
    private String workLocation;

    /**
     * 工作类型（兼容优化器字段名）
     */
    private String workType;

    /**
     * 扩展属性（兼容优化器字段名）
     */
    private Map<String, Object> attributes;

    /**
     * 排班优先级
     */
    private Integer priority;

    /**
     * 是否自动生成
     */
    private Boolean autoGenerated;

    /**
     * 排班来源
     */
    private String source;

    /**
     * 排班状态
     */
    private String status;

    /**
     * 分配时间
     */
    private LocalDateTime assignedTime;

    /**
     * 使用的算法
     */
    private String algorithmUsed;

    /**
     * 适应度评分（用于遗传算法等）
     */
    private Double fitnessScore;

    /**
     * 实际工作时长（分钟）
     */
    private Integer actualDuration;

    /**
     * 创建时间
     */
    private LocalDateTime createdTime;

    /**
     * 更新时间
     */
    private LocalDateTime updatedTime;

    /**
     * 扩展属性
     */
    private String extendedAttributes;
}
