-- ============================================================
-- IOE-DREAM Common Service - System模块
-- 表名: t_employee (员工表)
-- 功能: 企业员工档案管理
-- 创建时间: 2025-12-02
-- ============================================================

CREATE TABLE IF NOT EXISTS `t_employee` (
    `employee_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '员工ID',
    `user_id` BIGINT COMMENT '关联用户ID（外键关联t_user表）',
    `employee_no` VARCHAR(50) NOT NULL COMMENT '员工工号（唯一）',
    `employee_name` VARCHAR(100) NOT NULL COMMENT '员工姓名',
    `gender` TINYINT COMMENT '性别：1-男 2-女 3-未知',
    `birth_date` DATE COMMENT '出生日期',
    `id_card_no` VARCHAR(18) COMMENT '身份证号',
    `phone` VARCHAR(20) NOT NULL COMMENT '手机号',
    `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
    `department_id` BIGINT NOT NULL COMMENT '部门ID',
    `department_name` VARCHAR(100) COMMENT '部门名称（冗余字段）',
    `position` VARCHAR(100) NOT NULL COMMENT '职位/岗位',
    `job_level` VARCHAR(50) COMMENT '职级',
    `supervisor_id` BIGINT COMMENT '直属上级ID',
    `supervisor_name` VARCHAR(100) COMMENT '直属上级姓名（冗余字段）',
    `hire_date` DATE NOT NULL COMMENT '入职日期',
    `regular_date` DATE COMMENT '转正日期',
    `resign_date` DATE COMMENT '离职日期',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '员工状态：1-在职 2-离职 3-休假 4-停职',
    `employee_type` TINYINT NOT NULL DEFAULT 1 COMMENT '员工类型：1-正式 2-实习 3-外包 4-兼职',
    `work_location` VARCHAR(200) COMMENT '工作地点',
    `work_phone` VARCHAR(20) COMMENT '工作电话',
    `emergency_contact` VARCHAR(100) COMMENT '紧急联系人',
    `emergency_phone` VARCHAR(20) COMMENT '紧急联系电话',
    `home_address` VARCHAR(500) COMMENT '家庭住址',
    `education` TINYINT COMMENT '学历：1-高中 2-大专 3-本科 4-硕士 5-博士',
    `graduate_school` VARCHAR(200) COMMENT '毕业院校',
    `major` VARCHAR(100) COMMENT '专业',
    `work_experience` INT COMMENT '工作经验（年）',
    `skills` TEXT COMMENT '技能标签（JSON格式）',
    `contract_type` TINYINT COMMENT '合同类型：1-劳动合同 2-劳务合同 3-实习协议',
    `contract_start_date` DATE COMMENT '合同开始日期',
    `contract_end_date` DATE COMMENT '合同结束日期',
    `social_security_no` VARCHAR(50) COMMENT '社保账号',
    `housing_fund_no` VARCHAR(50) COMMENT '公积金账号',
    `bank_card_no` VARCHAR(50) COMMENT '银行卡号',
    `bank_name` VARCHAR(100) COMMENT '开户银行',
    `avatar` VARCHAR(500) COMMENT '头像URL',
    `remark` VARCHAR(500) COMMENT '备注',
    `extended_fields` TEXT COMMENT '扩展字段（JSON格式）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT COMMENT '创建人ID',
    `update_user_id` BIGINT COMMENT '更新人ID',
    `deleted_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0-未删除 1-已删除',
    PRIMARY KEY (`employee_id`),
    UNIQUE KEY `uk_employee_no` (`employee_no`),
    UNIQUE KEY `uk_user_id` (`user_id`),
    KEY `idx_phone` (`phone`),
    KEY `idx_email` (`email`),
    KEY `idx_id_card_no` (`id_card_no`),
    KEY `idx_department_id` (`department_id`),
    KEY `idx_supervisor_id` (`supervisor_id`),
    KEY `idx_status` (`status`),
    KEY `idx_employee_type` (`employee_type`),
    KEY `idx_hire_date` (`hire_date`),
    KEY `idx_deleted_flag` (`deleted_flag`),
    CONSTRAINT `fk_employee_user` FOREIGN KEY (`user_id`) REFERENCES `t_user` (`user_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工表-企业员工档案管理';

