name: Local Upload Artifact
description: Local replacement for actions/upload-artifact
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Artifact paths
    required: true
  retention-days:
    description: Retention days
    required: false
runs:
  using: composite
  steps:
    - name: Upload Artifact (bash)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        NAME="${INPUT_NAME:-artifact}"
        PATHS="${INPUT_PATH:-}"
        DEST="artifacts/${NAME}"
        mkdir -p "$DEST"
        shopt -s nullglob globstar
        found=0
        while IFS= read -r pattern; do
          [ -z "$pattern" ] && continue
          matches=( $pattern )
          if [ ${#matches[@]} -eq 0 ]; then
            continue
          fi
          for m in "${matches[@]}"; do
            if [ -e "$m" ]; then
              found=1
              cp -R "$m" "$DEST/"
            fi
          done
        done <<< "$PATHS"
        if [ "$found" -eq 0 ]; then
          echo "No artifacts matched: $PATHS"
        else
          echo "Artifacts copied to $DEST"
        fi
    - name: Upload Artifact (pwsh)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        $name = $env:INPUT_NAME
        if ([string]::IsNullOrWhiteSpace($name)) { $name = "artifact" }
        $paths = $env:INPUT_PATH
        $dest = Join-Path -Path "artifacts" -ChildPath $name
        New-Item -ItemType Directory -Path $dest -Force | Out-Null
        $found = $false
        foreach ($pattern in ($paths -split "`n")) {
          if ([string]::IsNullOrWhiteSpace($pattern)) { continue }
          $items = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue
          foreach ($item in $items) {
            $found = $true
            Copy-Item -Path $item.FullName -Destination $dest -Recurse -Force
          }
        }
        if (-not $found) {
          Write-Host "No artifacts matched: $paths"
        } else {
          Write-Host "Artifacts copied to $dest"
        }
