-- 考勤异常表
CREATE TABLE `t_attendance_exception` (
  `exception_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '异常ID',
  `record_id` bigint(20) DEFAULT NULL COMMENT '关联考勤记录ID',
  `employee_id` bigint(20) NOT NULL COMMENT '员工ID',
  `exception_date` date NOT NULL COMMENT '异常日期',
  `exception_type` varchar(50) NOT NULL COMMENT '异常类型: LATE-迟到, EARLY_LEAVE-早退, ABSENTEEISM-旷工, FORGET_PUNCH-忘打卡, OUTSIDE_LOCATION-位置异常',
  `exception_level` varchar(20) DEFAULT 'NORMAL' COMMENT '异常级别: LOW-低, NORMAL-一般, HIGH-高, CRITICAL-严重',
  `exception_description` varchar(500) NOT NULL COMMENT '异常描述',
  `original_time` time DEFAULT NULL COMMENT '原始打卡时间',
  `expected_time` time DEFAULT NULL COMMENT '预期打卡时间',
  `late_minutes` int(11) DEFAULT NULL COMMENT '迟到分钟数',
  `early_minutes` int(11) DEFAULT NULL COMMENT '早退分钟数',
  `exception_reason` varchar(500) DEFAULT NULL COMMENT '异常原因',
  `employee_remark` varchar(500) DEFAULT NULL COMMENT '员工备注',
  `location_info` json DEFAULT NULL COMMENT '位置信息: {latitude: 39.9042, longitude: 116.4074, address: "详细地址"}',
  `device_info` json DEFAULT NULL COMMENT '设备信息: {deviceId: "xxx", deviceType: "mobile", appVersion: "1.0.0"}',
  `evidence_files` json DEFAULT NULL COMMENT '证明文件: [{type: "image", url: "/files/evidence1.jpg"}]',
  `auto_detected` tinyint(1) DEFAULT '1' COMMENT '是否自动检测: 0-手动, 1-自动',
  `detection_rule` varchar(100) DEFAULT NULL COMMENT '检测规则',
  `status` varchar(20) DEFAULT 'PENDING' COMMENT '处理状态: PENDING-待处理, APPROVED-已批准, REJECTED-已拒绝, PROCESSING-处理中',
  `process_type` varchar(50) DEFAULT NULL COMMENT '处理方式: AUTO_APPROVAL-自动批准, MANUAL-人工处理, SYSTEM-系统处理',
  `applied_by` bigint(20) DEFAULT NULL COMMENT '申请人ID',
  `applied_by_name` varchar(50) DEFAULT NULL COMMENT '申请人姓名',
  `applied_time` datetime DEFAULT NULL COMMENT '申请时间',
  `processed_by` bigint(20) DEFAULT NULL COMMENT '处理人ID',
  `processed_by_name` varchar(50) DEFAULT NULL COMMENT '处理人姓名',
  `processed_time` datetime DEFAULT NULL COMMENT '处理时间',
  `process_result` varchar(500) DEFAULT NULL COMMENT '处理结果',
  `process_remark` varchar(500) DEFAULT NULL COMMENT '处理备注',
  `is_valid` tinyint(1) DEFAULT '1' COMMENT '是否有效异常: 0-无效, 1-有效',
  `need_follow_up` tinyint(1) DEFAULT '0' COMMENT '是否需要跟进: 0-否, 1-是',
  `follow_up_time` datetime DEFAULT NULL COMMENT '跟进时间',
  `notification_sent` tinyint(1) DEFAULT '0' COMMENT '是否已发送通知: 0-否, 1-是',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0-正常 1-删除',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`exception_id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_employee_id` (`employee_id`),
  KEY `idx_exception_date` (`exception_date`),
  KEY `idx_exception_type` (`exception_type`),
  KEY `idx_status` (`status`),
  KEY `idx_processed_by` (`processed_by`),
  KEY `idx_create_time` (`create_time`),
  CONSTRAINT `fk_attendance_exception_record` FOREIGN KEY (`record_id`) REFERENCES `t_attendance_record` (`record_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_attendance_exception_employee` FOREIGN KEY (`employee_id`) REFERENCES `t_hr_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='考勤异常表';

-- 异常处理流程表
CREATE TABLE `t_attendance_exception_process` (
  `process_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '处理ID',
  `exception_id` bigint(20) NOT NULL COMMENT '异常ID',
  `process_step` varchar(50) NOT NULL COMMENT '处理步骤: DETECTION-检测, NOTIFICATION-通知, REVIEW-审核, APPROVAL-批准, EXECUTION-执行',
  `process_status` varchar(20) NOT NULL COMMENT '步骤状态: PENDING-待处理, IN_PROGRESS-进行中, COMPLETED-已完成, FAILED-失败',
  `processor_id` bigint(20) DEFAULT NULL COMMENT '处理人ID',
  `processor_name` varchar(50) DEFAULT NULL COMMENT '处理人姓名',
  `process_time` datetime DEFAULT NULL COMMENT '处理时间',
  `process_result` varchar(500) DEFAULT NULL COMMENT '处理结果',
  `process_remark` varchar(500) DEFAULT NULL COMMENT '处理备注',
  `attachments` json DEFAULT NULL COMMENT '附件信息',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`process_id`),
  KEY `idx_exception_id` (`exception_id`),
  KEY `idx_processor_id` (`processor_id`),
  KEY `idx_process_step` (`process_step`),
  KEY `idx_process_time` (`process_time`),
  CONSTRAINT `fk_attendance_exception_process_exception` FOREIGN KEY (`exception_id`) REFERENCES `t_attendance_exception` (`exception_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='异常处理流程表';