-- 排班管理表
CREATE TABLE `t_attendance_schedule` (
  `schedule_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '排班ID',
  `employee_id` bigint(20) NOT NULL COMMENT '员工ID',
  `schedule_date` date NOT NULL COMMENT '排班日期',
  `shift_id` bigint(20) NOT NULL COMMENT '班次ID',
  `shift_name` varchar(50) NOT NULL COMMENT '班次名称',
  `work_start_time` time NOT NULL COMMENT '工作开始时间',
  `work_end_time` time NOT NULL COMMENT '工作结束时间',
  `break_start_time` time DEFAULT NULL COMMENT '休息开始时间',
  `break_end_time` time DEFAULT NULL COMMENT '休息结束时间',
  `work_hours` decimal(4,2) NOT NULL COMMENT '工作时长(小时)',
  `break_hours` decimal(4,2) DEFAULT '0.00' COMMENT '休息时长(小时)',
  `is_holiday` tinyint(1) DEFAULT '0' COMMENT '是否节假日: 0-否, 1-是',
  `is_overtime_day` tinyint(1) DEFAULT '0' COMMENT '是否加班日: 0-否, 1-是',
  `is_weekend` tinyint(1) DEFAULT '0' COMMENT '是否周末: 0-否, 1-是',
  `schedule_type` varchar(20) DEFAULT 'NORMAL' COMMENT '排班类型: NORMAL-正常, OVERTIME-加班, HOLIDAY-节假日, LEAVE-请假',
  `overtime_rate` decimal(3,2) DEFAULT '1.00' COMMENT '加班倍率',
  `location_id` bigint(20) DEFAULT NULL COMMENT '工作地点ID',
  `location_name` varchar(100) DEFAULT NULL COMMENT '工作地点名称',
  `supervisor_id` bigint(20) DEFAULT NULL COMMENT '主管ID',
  `supervisor_name` varchar(50) DEFAULT NULL COMMENT '主管姓名',
  `remarks` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0-正常 1-删除',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`schedule_id`),
  UNIQUE KEY `uk_employee_date` (`employee_id`, `schedule_date`),
  KEY `idx_schedule_date` (`schedule_date`),
  KEY `idx_shift_id` (`shift_id`),
  KEY `idx_employee_id` (`employee_id`),
  KEY `idx_schedule_type` (`schedule_type`),
  KEY `idx_supervisor_id` (`supervisor_id`),
  KEY `idx_location_id` (`location_id`),
  CONSTRAINT `fk_attendance_schedule_employee` FOREIGN KEY (`employee_id`) REFERENCES `t_hr_employee` (`employee_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_attendance_schedule_shift` FOREIGN KEY (`shift_id`) REFERENCES `t_attendance_shift` (`shift_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='排班管理表';

-- 班次表
CREATE TABLE `t_attendance_shift` (
  `shift_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '班次ID',
  `shift_name` varchar(50) NOT NULL COMMENT '班次名称',
  `shift_code` varchar(20) NOT NULL COMMENT '班次编码',
  `company_id` bigint(20) NOT NULL COMMENT '公司ID',
  `work_start_time` time NOT NULL COMMENT '工作开始时间',
  `work_end_time` time NOT NULL COMMENT '工作结束时间',
  `break_start_time` time DEFAULT NULL COMMENT '休息开始时间',
  `break_end_time` time DEFAULT NULL COMMENT '休息结束时间',
  `work_hours` decimal(4,2) NOT NULL COMMENT '工作时长(小时)',
  `is_flexible` tinyint(1) DEFAULT '0' COMMENT '是否弹性工作制: 0-否, 1-是',
  `flex_start_time` time DEFAULT NULL COMMENT '弹性上班最早时间',
  `flex_end_time` time DEFAULT NULL COMMENT '弹性上班最晚时间',
  `cross_day` tinyint(1) DEFAULT '0' COMMENT '是否跨天: 0-否, 1-是',
  `night_shift` tinyint(1) DEFAULT '0' COMMENT '是否夜班: 0-否, 1-是',
  `overtime_rate` decimal(3,2) DEFAULT '1.00' COMMENT '加班倍率',
  `description` varchar(200) DEFAULT NULL COMMENT '班次描述',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE-激活, INACTIVE-停用',
  `sort_order` int(11) DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0-正常 1-删除',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`shift_id`),
  UNIQUE KEY `uk_shift_code` (`shift_code`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='班次表';