-- 考勤规则表
CREATE TABLE `t_attendance_rule` (
  `rule_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '规则ID',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `rule_code` varchar(50) NOT NULL COMMENT '规则编码',
  `company_id` bigint(20) NOT NULL COMMENT '公司ID',
  `department_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `employee_id` bigint(20) DEFAULT NULL COMMENT '员工ID(个人规则时使用)',
  `rule_type` varchar(20) NOT NULL DEFAULT 'GLOBAL' COMMENT '规则类型: GLOBAL-全局, DEPARTMENT-部门, INDIVIDUAL-个人',
  `employee_type` varchar(50) DEFAULT NULL COMMENT '适用员工类型: FULL_TIME-全职, PART_TIME-兼职, INTERN-实习',
  `work_schedule` json NOT NULL COMMENT '工作排班配置: {workDays:[1,2,3,4,5], workStartTime:"09:00", workEndTime:"18:00"}',
  `late_tolerance` int(11) DEFAULT '0' COMMENT '迟到容忍分钟数',
  `early_tolerance` int(11) DEFAULT '0' COMMENT '早退容忍分钟数',
  `overtime_rules` json DEFAULT NULL COMMENT '加班规则配置: {enabled:true, minOvertimeMinutes:30, doublePayHours:2}',
  `holiday_rules` json DEFAULT NULL COMMENT '节假日规则配置: {holidays:[], overtimeRate:2.0}',
  `gps_validation` tinyint(1) DEFAULT '0' COMMENT '是否启用GPS验证: 0-否, 1-是',
  `gps_locations` json DEFAULT NULL COMMENT 'GPS位置配置: [{name:"主办公区", latitude:39.9042, longitude:116.4074, radius:100}]',
  `gps_range` int(11) DEFAULT '100' COMMENT 'GPS验证范围(米)',
  `photo_required` tinyint(1) DEFAULT '0' COMMENT '是否需要拍照打卡: 0-否, 1-是',
  `face_recognition` tinyint(1) DEFAULT '0' COMMENT '是否启用人脸识别: 0-否, 1-是',
  `device_restrictions` json DEFAULT NULL COMMENT '设备限制配置: {allowedDevices:[], maxDeviceCount:3}',
  `auto_approval` tinyint(1) DEFAULT '0' COMMENT '是否自动审批异常: 0-否, 1-是',
  `notification_settings` json DEFAULT NULL COMMENT '通知设置: {late:true, absent:true, overtime:true}',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '规则状态: ACTIVE-激活, INACTIVE-停用, DRAFT-草稿',
  `effective_date` date NOT NULL COMMENT '生效日期',
  `expiry_date` date DEFAULT NULL COMMENT '失效日期',
  `priority` int(11) DEFAULT '0' COMMENT '优先级(数字越大优先级越高)',
  `description` varchar(500) DEFAULT NULL COMMENT '规则描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0-正常 1-删除',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`rule_id`),
  UNIQUE KEY `uk_rule_code` (`rule_code`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_employee_id` (`employee_id`),
  KEY `idx_rule_type` (`rule_type`),
  KEY `idx_status` (`status`),
  KEY `idx_effective_date` (`effective_date`),
  KEY `idx_priority` (`priority`),
  CONSTRAINT `fk_attendance_rule_company` FOREIGN KEY (`company_id`) REFERENCES `t_sys_company` (`company_id`),
  CONSTRAINT `fk_attendance_rule_department` FOREIGN KEY (`department_id`) REFERENCES `t_sys_department` (`department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='考勤规则表';