-- 考勤统计表
CREATE TABLE `t_attendance_statistics` (
  `statistics_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '统计ID',
  `employee_id` bigint(20) NOT NULL COMMENT '员工ID',
  `department_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `company_id` bigint(20) NOT NULL COMMENT '公司ID',
  `statistics_type` varchar(20) NOT NULL COMMENT '统计类型: DAILY-日报, WEEKLY-周报, MONTHLY-月报, QUARTERLY-季报, YEARLY-年报',
  `statistics_period` varchar(20) NOT NULL COMMENT '统计周期: 2024-01, 2024-W01',
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `year` int(4) NOT NULL COMMENT '年份',
  `month` int(2) DEFAULT NULL COMMENT '月份',
  `quarter` int(1) DEFAULT NULL COMMENT '季度',
  `week` int(2) DEFAULT NULL COMMENT '周数',
  `total_days` int(11) DEFAULT '0' COMMENT '总天数',
  `work_days` int(11) DEFAULT '0' COMMENT '工作天数',
  `actual_work_days` int(11) DEFAULT '0' COMMENT '实际工作天数',
  `present_days` int(11) DEFAULT '0' COMMENT '出勤天数',
  `absent_days` int(11) DEFAULT '0' COMMENT '缺勤天数',
  `leave_days` int(11) DEFAULT '0' COMMENT '请假天数',
  `holiday_days` int(11) DEFAULT '0' COMMENT '节假日天数',
  `late_days` int(11) DEFAULT '0' COMMENT '迟到天数',
  `early_leave_days` int(11) DEFAULT '0' COMMENT '早退天数',
  `overtime_days` int(11) DEFAULT '0' COMMENT '加班天数',
  `forget_punch_days` int(11) DEFAULT '0' COMMENT '忘打卡天数',
  `total_work_hours` decimal(8,2) DEFAULT '0.00' COMMENT '总工作时长(小时)',
  `actual_work_hours` decimal(8,2) DEFAULT '0.00' COMMENT '实际工作时长(小时)',
  `standard_work_hours` decimal(8,2) DEFAULT '0.00' COMMENT '标准工作时长(小时)',
  `overtime_hours` decimal(8,2) DEFAULT '0.00' COMMENT '加班时长(小时)',
  `overtime_weekend_hours` decimal(8,2) DEFAULT '0.00' COMMENT '周末加班时长(小时)',
  `overtime_holiday_hours` decimal(8,2) DEFAULT '0.00' COMMENT '节假日加班时长(小时)',
  `late_total_minutes` int(11) DEFAULT '0' COMMENT '迟到总分钟数',
  `early_leave_total_minutes` int(11) DEFAULT '0' COMMENT '早退总分钟数',
  `attendance_rate` decimal(5,2) DEFAULT '0.00' COMMENT '出勤率(%)',
  `punctuality_rate` decimal(5,2) DEFAULT '0.00' COMMENT '准时率(%)',
  `efficiency_rate` decimal(5,2) DEFAULT '0.00' COMMENT '工作效率(%)',
  `abnormal_rate` decimal(5,2) DEFAULT '0.00' COMMENT '异常率(%)',
  `average_work_hours` decimal(4,2) DEFAULT '0.00' COMMENT '平均工作时长(小时)',
  `max_continuous_work_days` int(11) DEFAULT '0' COMMENT '最长连续工作天数',
  `leave_balance` decimal(4,2) DEFAULT '0.00' COMMENT '假期余额(天)',
  `sick_leave_used` decimal(4,2) DEFAULT '0.00' COMMENT '已用病假(天)',
  `annual_leave_used` decimal(4,2) DEFAULT '0.00' COMMENT '已用年假(天)',
  `personal_leave_used` decimal(4,2) DEFAULT '0.00' COMMENT '已用事假(天)',
  `performance_score` decimal(5,2) DEFAULT NULL COMMENT '绩效得分',
  `ranking` int(11) DEFAULT NULL COMMENT '排名',
  `ranking_percentile` decimal(5,2) DEFAULT NULL COMMENT '排名百分位',
  `trend_month_over_month` decimal(5,2) DEFAULT NULL COMMENT '环比增长率(%)',
  `trend_year_over_year` decimal(5,2) DEFAULT NULL COMMENT '同比增长率(%)',
  `quality_score` decimal(5,2) DEFAULT NULL COMMENT '考勤质量得分',
  `risk_level` varchar(20) DEFAULT NULL COMMENT '风险等级: LOW-低, MEDIUM-中, HIGH-高',
  `recommendations` json DEFAULT NULL COMMENT '改进建议',
  `metrics_data` json DEFAULT NULL COMMENT '详细指标数据',
  `created_by_system` tinyint(1) DEFAULT '1' COMMENT '是否系统生成: 0-手动, 1-系统',
  `last_calculated_time` datetime DEFAULT NULL COMMENT '最后计算时间',
  `calculation_status` varchar(20) DEFAULT 'PENDING' COMMENT '计算状态: PENDING-待计算, CALCULATING-计算中, COMPLETED-已完成, FAILED-失败',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0-正常 1-删除',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`statistics_id`),
  UNIQUE KEY `uk_employee_period_type` (`employee_id`, `statistics_period`, `statistics_type`),
  KEY `idx_employee_id` (`employee_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_statistics_type` (`statistics_type`),
  KEY `idx_statistics_date` (`statistics_date`),
  KEY `idx_year` (`year`),
  KEY `idx_month` (`month`),
  KEY `idx_create_time` (`create_time`),
  CONSTRAINT `fk_attendance_statistics_employee` FOREIGN KEY (`employee_id`) REFERENCES `t_hr_employee` (`employee_id`),
  CONSTRAINT `fk_attendance_statistics_department` FOREIGN KEY (`department_id`) REFERENCES `t_sys_department` (`department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='考勤统计表';

-- 部门考勤汇总表
CREATE TABLE `t_attendance_department_summary` (
  `summary_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '汇总ID',
  `department_id` bigint(20) NOT NULL COMMENT '部门ID',
  `company_id` bigint(20) NOT NULL COMMENT '公司ID',
  `statistics_period` varchar(20) NOT NULL COMMENT '统计周期',
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `total_employees` int(11) DEFAULT '0' COMMENT '总员工数',
  `active_employees` int(11) DEFAULT '0' COMMENT '在职员工数',
  `present_employees` int(11) DEFAULT '0' COMMENT '出勤员工数',
  `absent_employees` int(11) DEFAULT '0' COMMENT '缺勤员工数',
  `late_employees` int(11) DEFAULT '0' COMMENT '迟到员工数',
  `early_leave_employees` int(11) DEFAULT '0' COMMENT '早退员工数',
  `leave_employees` int(11) DEFAULT '0' COMMENT '请假员工数',
  `department_attendance_rate` decimal(5,2) DEFAULT '0.00' COMMENT '部门出勤率(%)',
  `department_punctuality_rate` decimal(5,2) DEFAULT '0.00' COMMENT '部门准时率(%)',
  `department_overtime_hours` decimal(8,2) DEFAULT '0.00' COMMENT '部门加班总时长(小时)',
  `department_avg_work_hours` decimal(4,2) DEFAULT '0.00' COMMENT '部门平均工作时长(小时)',
  `department_performance_score` decimal(5,2) DEFAULT NULL COMMENT '部门绩效得分',
  `department_ranking` int(11) DEFAULT NULL COMMENT '部门排名',
  `metrics_comparison` json DEFAULT NULL COMMENT '指标对比数据',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0-正常 1-删除',
  PRIMARY KEY (`summary_id`),
  UNIQUE KEY `uk_department_period` (`department_id`, `statistics_period`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_statistics_period` (`statistics_period`),
  KEY `idx_create_time` (`create_time`),
  CONSTRAINT `fk_attendance_dept_summary_department` FOREIGN KEY (`department_id`) REFERENCES `t_sys_department` (`department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='部门考勤汇总表';