name: Local SonarCloud
description: Local replacement for SonarSource/sonarcloud-github-action
inputs:
  args:
    description: Sonar arguments
    required: false
runs:
  using: composite
  steps:
    - name: Sonar scan (bash)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        ARGS="${INPUT_ARGS:-}"
        if command -v sonar-scanner >/dev/null 2>&1; then
          sonar-scanner $ARGS
        else
          mvn -B sonar:sonar $ARGS
        fi
    - name: Sonar scan (pwsh)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        $args = $env:INPUT_ARGS
        $scanner = Get-Command sonar-scanner -ErrorAction SilentlyContinue
        if ($null -ne $scanner) {
          sonar-scanner $args
        } else {
          mvn -B sonar:sonar $args
        }
